### ISSUE TITLE
Hangs forever

### ISSUE THREAD

**Issue by vyasakshay** [sshtools/j2ssh-maverick#20]
Trying to unload a task on a remote macOS machine. The thread hangs forever on the shellprocess drain method.
**Logs:**
DEBUG - There are now 2 active connections on client connection manager
DEBUG - Firing EVENT_CONNECTED success=true
DEBUG - Sent local identification string SSH-2.0-MaverickSynergy
DEBUG - Remote client version OK
DEBUG - Firing EVENT_NEGOTIATED_PROTOCOL success=true
DEBUG - Posting SSH_MSG_KEX_INIT
DEBUG - Sent SSH_MSG_KEX_INIT
DEBUG - Received SSH_MSG_KEX_INIT
DEBUG - Remote Key Exchanges: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
DEBUG - Remote Public Keys: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
DEBUG - Remote Ciphers CS: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
DEBUG - Remote Ciphers SC: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
DEBUG - Remote Macs CS: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG - Remote Macs SC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG - Remote Compression CS: none,zlib@openssh.com
DEBUG - Remote Compression SC: none,zlib@openssh.com
DEBUG - Lang: 
DEBUG - First Packet Follows: false
DEBUG - Local Key Exchanges: diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,rsa2048-sha256,diffie-hellman-group14-sha1
DEBUG - Local Public Keys: ecdsa-sha2-nistp256,x509v3-ecdsa-sha2-nistp384,x509v3-ecdsa-sha2-nistp256,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,x509v3-ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,x509v3-sign-rsa-sha1,ssh-rsa,x509v3-sign-rsa,x509v3-ssh-rsa,x509v3-rsa2048-sha256,ssh-rsa-cert-v01@openssh.com,x509v3-ssh-dss,x509v3-sign-dss
DEBUG - Local Ciphers CS: aes256-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes192-ctr,aes128-ctr,3des-ctr
DEBUG - Local Ciphers SC: aes256-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes192-ctr,aes128-ctr,3des-ctr
DEBUG - Local Macs CS: hmac-sha2-512-etm@openssh.com,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96
DEBUG - Local Macs SC: hmac-sha2-512-etm@openssh.com,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96
DEBUG - Local Compression CS: none,zlib,zlib@openssh.com
DEBUG - Local Compression SC: none,zlib,zlib@openssh.com
DEBUG - Firing EVENT_KEY_EXCHANGE_INIT success=true
DEBUG - Negotiated Key Exchange: diffie-hellman-group-exchange-sha256
DEBUG - Negotiated Public Key: ecdsa-sha2-nistp256
DEBUG - Negotiated Cipher CS: aes256-ctr
DEBUG - Negotiated Cipher SC: aes256-ctr
DEBUG - Negotiated Mac CS: hmac-sha2-512-etm@openssh.com
DEBUG - Negotiated Mac SC: hmac-sha2-512-etm@openssh.com
DEBUG - Negotiated Compression CS: none
DEBUG - Negotiated Compression SC: none
DEBUG - Minimum DH prime size is 2048
DEBUG - Preferred DH prime size is 2048
DEBUG - Maximum DH prime size is 8192
DEBUG - Sent SSH_MSG_KEY_DH_GEX_REQUEST
DEBUG - Received 2048 bit DH prime with group 2
DEBUG - Sent SSH_MSG_KEXDH_INIT
DEBUG - Verifying server DH parameters
DEBUG - Verified DH parameters. Performing DH calculations
DEBUG - Verifying calculated DH parameters
DEBUG - Calculating exchange hash
DEBUG - Completed key exchange calculations
DEBUG - Received SSH_MSG_NEWKEYS
DEBUG - Sent SSH_MSG_NEWKEYS
DEBUG - Firing EVENT_HOSTKEY_ACCEPTED success=true
DEBUG - Firing EVENT_KEY_EXCHANGE_COMPLETE success=true
DEBUG - Sent SSH_MSG_SERVICE_REQUEST ssh-userauth
DEBUG - Starting Authentication Protocol
DEBUG - Starting none authentication
DEBUG - SSH_MSG_USERAUTH_FAILURE received auths=publickey,password,keyboard-interactive
DEBUG - none authentication failed
DEBUG - Authenticating with password
DEBUG - Adding password authentication
DEBUG - We prefer keyboard-interactive over password so injecting keyboard-interactive authenticator
DEBUG - Starting keyboard-interactive authentication
DEBUG - SSH_MSG_USERAUTH_INFO_REQUEST received
DEBUG - SSH_MSG_USERAUTH_INFO_RESPONSE sent
DEBUG - SSH_MSG_USERAUTH_INFO_REQUEST received
DEBUG - SSH_MSG_USERAUTH_INFO_RESPONSE sent
DEBUG - SSH_MSG_USERAUTH_SUCCESS received
DEBUG - Initialized MaxChannels=100
DEBUG - Stopping Authentication Protocol
DEBUG - keyboard-interactive authentication succeeded
DEBUG - Authentication succeeded
DEBUG - Sent SSH_MSG_CHANNEL_OPEN channel=0 channelType=session
DEBUG - Received SSH_MSG_GLOBAL_REQUEST request=hostkeys-00@openssh.com wantReply=false
DEBUG - Received SSH_MSG_CHANNEL_OPEN_CONFIRMATION channel=0 remote=0 remotepacket=32768 remotewindow=0
DEBUG - Starting session task
DEBUG - Creating session for interactive shell
DEBUG - Sent SSH_MSG_CHANNEL_REQUEST request=pty-req wantReply=true channel=0 remote=0 localWindow=1024000 remoteWindow=0
DEBUG - Sent SSH_MSG_CHANNEL_REQUEST request=shell wantReply=true channel=0 remote=0 localWindow=1024000 remoteWindow=0
DEBUG - Received SSH_MSG_CHANNEL_SUCCESS channel=0 remote=0 localWindow=1024000 remoteWindow=0
DEBUG - Received SSH_MSG_CHANNEL_WINDOW_ADJUST channel=0 remote=0 adjust=2097152
DEBUG - Received SSH_MSG_CHANNEL_SUCCESS channel=0 remote=0 localWindow=1024000 remoteWindow=2097152
DEBUG - Received SSH_MSG_CHANNEL_DATA len=57 channel=0 remote=0 localWindow=1023943 remoteWindow=2097152
DEBUG - Received SSH_MSG_CHANNEL_DATA len=183 channel=0 remote=0 localWindow=1023760 remoteWindow=2097152
DEBUG - Received SSH_MSG_CHANNEL_DATA len=26 channel=0 remote=0 localWindow=1023734 remoteWindow=2097152
DEBUG - Performing marker test: echo "---BEGIN---" ; echo $?
DEBUG - Sent SSH_MSG_CHANNEL_DATA seq=12 len=30 channel=0 remote=0 localWindow=1023734 remoteWindow=2097122
DEBUG - Session creation complete
DEBUG - Checking state of startup controller
DEBUG - Shell still in startup mode, draining startup output
DEBUG - Shell startup (read): Last login: Sat Jun 24 11:00:53 2023 from 192.168.1.18

DEBUG - Shell startup (read): 
DEBUG - Shell startup (read): The default interactive shell is now zsh.
DEBUG - Shell startup (read): To update your account to use zsh, please run `chsh -s /bin/zsh`.
DEBUG - Shell startup (read): For more details, please visit https://support.apple.com/kb/HT208050.
DEBUG - Received SSH_MSG_CHANNEL_DATA len=10 channel=0 remote=0 localWindow=1023724 remoteWindow=2097122
DEBUG - Received SSH_MSG_CHANNEL_DATA len=6 channel=0 remote=0 localWindow=1023718 remoteWindow=2097122
DEBUG - Received SSH_MSG_CHANNEL_DATA len=8 channel=0 remote=0 localWindow=1023710 remoteWindow=2097122
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023706 remoteWindow=2097122
DEBUG - Potentially found test marker [<machine_name>:~ akshay$ echo "---BEGIN---]
DEBUG - Detected echo of test marker command since we did not find LF at end of marker ch=34 currentLine=<machine_name>:~ akshay$ echo "---BEGIN---
DEBUG - Received SSH_MSG_CHANNEL_DATA len=2 channel=0 remote=0 localWindow=1023704 remoteWindow=2097122
DEBUG - Received SSH_MSG_CHANNEL_DATA len=16 channel=0 remote=0 localWindow=1023688 remoteWindow=2097122
DEBUG - Shell startup (read): <machine_name>:~ akshay$ echo "---BEGIN---" ; echo $?
DEBUG - Potentially found test marker [---BEGIN---]
DEBUG - Looking good, found CR
DEBUG - Found test marker
DEBUG - Detecting shell settings
DEBUG - Shell startup (detect): 0
DEBUG - This looks like a *nix type machine, setting EOL to CR only and exit code variable to $?
DEBUG - Checking state of startup controller
DEBUG - Shell is ready for command
DEBUG - Executing command: uname
DEBUG - Executing raw command: echo "---BEGIN---"; uname; echo "---END---;PROCESS=1687584933178;EXITCODE=$?"

DEBUG - Received SSH_MSG_CHANNEL_DATA len=26 channel=0 remote=0 localWindow=1023662 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=2 channel=0 remote=0 localWindow=1023660 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=26 channel=0 remote=0 localWindow=1023634 remoteWindow=2097044
DEBUG - Sent SSH_MSG_CHANNEL_DATA seq=13 len=78 channel=0 remote=0 localWindow=1023634 remoteWindow=2097044
DEBUG - uname: Expecting begin marker
DEBUG - Received SSH_MSG_CHANNEL_DATA len=9 channel=0 remote=0 localWindow=1023625 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=5 channel=0 remote=0 localWindow=1023620 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=7 channel=0 remote=0 localWindow=1023613 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023609 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023606 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023603 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023599 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023596 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023592 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023589 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023585 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023581 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023578 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023575 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023572 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023568 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023565 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023561 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023558 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023555 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=13 channel=0 remote=0 localWindow=1023542 remoteWindow=2097044
DEBUG - Received SSH_MSG_CHANNEL_DATA len=8 channel=0 remote=0 localWindow=1023534 remoteWindow=2097044
DEBUG - uname: Found begin marker
DEBUG - Received SSH_MSG_CHANNEL_DATA len=44 channel=0 remote=0 localWindow=1023490 remoteWindow=2097044
DEBUG - uname: ---END---;PROCESS=1687584933178;EXITCODE=
DEBUG - uname: Found end marker
DEBUG - uname: Looking for exit code
DEBUG - Received SSH_MSG_CHANNEL_DATA len=26 channel=0 remote=0 localWindow=1023464 remoteWindow=2097044
DEBUG - uname: Exit code is 0
DEBUG - Remote side reported it is Darwin
DEBUG - Setting default sudo prompt
DEBUG - Checking state of startup controller
DEBUG - Shell is ready for command
DEBUG - Executing command: export SUDO_PROMPT=Password:
DEBUG - Executing raw command: echo "---BEGIN---"; export SUDO_PROMPT=Password:; echo "---END---;PROCESS=1687584933190;EXITCODE=$?"

DEBUG - Sent SSH_MSG_CHANNEL_DATA seq=14 len=101 channel=0 remote=0 localWindow=1023464 remoteWindow=2096943
DEBUG - export SUDO_PROMPT=Password:: Expecting begin marker
DEBUG - Received SSH_MSG_CHANNEL_DATA len=7 channel=0 remote=0 localWindow=1023457 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=5 channel=0 remote=0 localWindow=1023452 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=7 channel=0 remote=0 localWindow=1023445 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023441 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023437 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023434 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023431 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023428 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023425 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023422 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023418 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023415 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023412 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023408 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=9 channel=0 remote=0 localWindow=1023399 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=11 channel=0 remote=0 localWindow=1023388 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023384 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023381 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023378 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023375 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023372 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023369 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023366 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023362 remoteWindow=2096943
DEBUG - Received SSH_MSG_CHANNEL_DATA len=57 channel=0 remote=0 localWindow=1023305 remoteWindow=2096943
DEBUG - export SUDO_PROMPT=Password:: Found begin marker
DEBUG - export SUDO_PROMPT=Password:: ---END---;PROCESS=1687584933190;EXITCODE=
DEBUG - export SUDO_PROMPT=Password:: Found end marker
DEBUG - export SUDO_PROMPT=Password:: Looking for exit code
DEBUG - export SUDO_PROMPT=Password:: Exit code is 0
DEBUG - Shell initialized
DEBUG - Shell is ready for command
DEBUG - Executing command: sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>
DEBUG - Received SSH_MSG_CHANNEL_DATA len=26 channel=0 remote=0 localWindow=1023279 remoteWindow=2096943
DEBUG - Executing raw command: echo "---BEGIN---"; sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>; echo "---END---;PROCESS=1687584933197;EXITCODE=$?"

DEBUG - Sent SSH_MSG_CHANNEL_DATA seq=15 len=173 channel=0 remote=0 localWindow=1023279 remoteWindow=2096770
DEBUG - sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>: Expecting begin marker
DEBUG - Received SSH_MSG_CHANNEL_DATA len=9 channel=0 remote=0 localWindow=1023270 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=5 channel=0 remote=0 localWindow=1023265 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=7 channel=0 remote=0 localWindow=1023258 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023255 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023251 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023248 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023244 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023241 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023238 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023235 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023231 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023228 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023225 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=2 channel=0 remote=0 localWindow=1023223 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023219 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023216 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023212 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023209 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023206 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023202 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023199 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023195 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023191 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=8 channel=0 remote=0 localWindow=1023183 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=6 channel=0 remote=0 localWindow=1023177 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023174 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023171 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023167 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023164 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023161 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023158 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023155 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023151 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023148 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023145 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023142 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023139 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023136 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023133 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023130 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023127 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023124 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=4 channel=0 remote=0 localWindow=1023120 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023117 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023114 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023111 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023108 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=3 channel=0 remote=0 localWindow=1023105 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=13 channel=0 remote=0 localWindow=1023092 remoteWindow=2096770
DEBUG - sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>: Found begin marker
DEBUG - Received SSH_MSG_CHANNEL_DATA len=44 channel=0 remote=0 localWindow=1023048 remoteWindow=2096770
DEBUG - Received SSH_MSG_CHANNEL_DATA len=26 channel=0 remote=0 localWindow=1023022 remoteWindow=2096770
DEBUG - sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>: ---END---;PROCESS=1687584933197;EXITCODE=
DEBUG - sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>: Found end marker
DEBUG - sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>: Looking for exit code
DEBUG - sudo launchctl unload -wF /Library/LaunchDaemons/<plist_file_path>: Exit code is 0
DEBUG - sudo password expression not matched
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com
DEBUG - There are 1 channels currently open
DEBUG - Sending SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Sent SSH_MSG_GLOBAL_REQUEST request=ping@sshtools.com wantReply=true
DEBUG - Received SSH_MSG_GLOBAL_REQUEST_FAILURE for ping@sshtools.com

**Thread Dump**
at java.lang.Object.wait(Native Method)
       at com.sshtools.synergy.ssh.CachingDataWindow.waitFor(CachingDataWindow.java:159)
       at com.sshtools.synergy.ssh.ChannelNG$ChannelInputStream.read(ChannelNG.java:1365)
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
       at com.sshtools.client.shell.ShellInputStream.read(ShellInputStream.java:145)
       at com.sshtools.client.shell.ShellProcess.drain(ShellProcess.java:82)

**Comment by vyasakshay** [comment]
Move to maverick synergy
