### ISSUE TITLE
Getting error while runtime

### ISSUE THREAD

**Issue by vyasakshay** [sshtools/j2ssh-maverick#21]
Getting this error while running. It seams you have compiled it with JDK higher than 8. When running the jar with version 8 throws this error.

 java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;|

 	at com.sshtools.synergy.nio.SocketConnection.processWriteEvent(SocketConnection.java:358)|

 	at com.sshtools.synergy.nio.SshEngine$SocketReadWriteTask.doTask(SshEngine.java:979)|

 	at com.sshtools.common.ssh.ConnectionAwareTask.run(ConnectionAwareTask.java:45)|

 	at com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask.executeAllTasks(ExecutorOperationSupport.java:127)|

 	at com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask.run(ExecutorOperationSupport.java:84)|

 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)|

 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)|

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)|

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)|

 	at java.lang.Thread.run(Thread.java:750)|

**Comment by vyasakshay** [comment]
Move to maverick synergy
