### ISSUE TITLE
com.sshtools.ssh.SshIOException

### ISSUE THREAD

**Issue by Pratappatil1992** [sshtools/j2ssh-maverick#6]
Hi,
SSH command execution success but getting following error while getting command execution result. 

Below is my code snippet.

```
public String getChannelOutput(InputStream inputStream) {
		InputStreamReader inputStreamReader = null;
		BufferedReader bufferedReader = null;
		StringBuilder builder = null;
		try {
			if(inputStream != null){
				inputStreamReader = new InputStreamReader(inputStream);
				bufferedReader = new BufferedReader(inputStreamReader);
				String line = bufferedReader.readLine();
				builder = new StringBuilder();
				while(line != null){
					builder.append(line);
					builder.append('\n');
					line = bufferedReader.readLine();
				}
				return builder.toString();
			}else{
				return "Channel input stream is null";
			}
		} catch (Exception e) {
			FlintLogger.JOB_LOGGER.error("Error in Channel output due to : "+e.getLocalizedMessage(),e);
			return "Error in Channel output due to : "+e.getLocalizedMessage();
		}finally{
			if(inputStreamReader != null){
				try {
					inputStreamReader.close();
				} catch (Exception e2) {
					FlintLogger.JOB_LOGGER.error("Exception occured while closing input stream reader",e2);
				}
				inputStreamReader = null;
			}
			if(bufferedReader != null){
				try {
					bufferedReader.close();
				} catch (Exception e2) {
					FlintLogger.JOB_LOGGER.error("Exception occured while closing buffered reader",e2);
				}
				bufferedReader =null;
			}
		}
	}
```

Call to above function : 
```
channelResult = session.getInputStream();
getChannelOutput(channelResult);   
```                                 
com.sshtools.ssh.SshIOException
at com.sshtools.ssh2.Ssh2Channel$ChannelInputStream.read(Ssh2Channel.java:1160) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_71]
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_71]
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_71]
at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_71]
at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_71]
at java.io.Buffere
dReader.readLine(BufferedReader.java:324) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_71]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.getChannelOutput(SSH2Helper.java:230) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.executeCommand(SSH2Helper.java:75) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Service.onRequest(SSH2Service.java:242) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.sdk.connectors.FlintConnectorBase.lambda$start$0(FlintConnectorBase.java:84) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91) ~[flint-lib-1.0.0.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
05-05-2016 13:09:20 IST ERROR [SSH2Helper.java:242] - Error in Channel output due to : null
com.sshtools.ssh.SshIOException
	at com.sshtools.ssh2.Ssh2Channel$ChannelInputStream.read(Ssh2Channel.java:1160) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_71]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_71]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_71]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_71]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_71]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.getChannelOutput(SSH2Helper.java:230) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.executeCommand(SSH2Helper.java:76) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Service.onRequest(SSH2Service.java:242) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.sdk.connectors.FlintConnectorBase.lambda$start$0(FlintConnectorBase.java:84) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91) ~[flint-lib-1.0.0.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by ludup** [comment]
The SshIoException will contain more information. There is a getRealException which returns an SshException that has a reason code and description. I suggest you catch that explicitly in your catch clause and process to get all the required information.

**Comment by Pratappatil1992** [comment]
As per you suggested I added e.getRealException in my catch clause.

Correct me if I am wrong that error occurred is only because of socket timeout
As I Set socket timeout of 60,000 millisecond and actual command execution taking more time than 60,000 millisecond.

 and following message printed by e.getRealException.

com.sshtools.ssh.SshException.: Socket connection timed out. [Unknown cause] com.sshtools.ssh.SshException: IO error received from remoteSocket closed [java.net.SocketException]

This is full stack trace of Exception.

com.sshtools.ssh.SshIOException
at com.sshtools.ssh2.Ssh2Channel$ChannelInputStream.read(Ssh2Channel.java:1160) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_71]
at sun.nio
.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_71]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_71]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_71]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_71]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.getChannelOutput(SSH2Helper.java:231) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.executeCommand(SSH2Helper.java:76) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Service.onRequest(SSH2Service.java:242) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.sdk.connectors.FlintConnectorBase.lambda$start$0(FlintConnectorBase.java:84) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91) ~[flint-lib-1.0.0.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
05-09-2016 12:56:44 IST ERROR [SSH2Helper.java:243] - SshIOException occured while getting channel result : com.sshtools.ssh.SshException: IO error received from remoteSocket closed [java.net.SocketException]
com.sshtools.ssh.SshIOException
	at com.sshtools.ssh2.Ssh2Channel$ChannelInputStream.read(Ssh2Channel.java:1160) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_71]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_71]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_71]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_71]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_71]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_71]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.getChannelOutput(SSH2Helper.java:231) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Helper.executeCommand(SSH2Helper.java:77) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.connector.ssh2.SSH2Service.onRequest(SSH2Service.java:242) ~[flint-ssh-connector-1.0.0.0-all.jar:?]
	at com.infiverve.flint.sdk.connectors.FlintConnectorBase.lambda$start$0(FlintConnectorBase.java:84) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335) ~[flint-lib-1.0.0.0-all.jar:?]
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91) ~[flint-lib-1.0.0.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

Awaiting for your reply
Thank you for your support.
