### ISSUE TITLE
EOF received from remote side

### ISSUE THREAD

**Issue by atharva-infiverve** [sshtools/j2ssh-maverick#9]
Hi,
We are using j2ssh maverick version-1.5.5 , but while connecting to remote linux server we are getting the following SshException: EOF received from remote side in stacktrace:

```
03-03-2017 16:01:57 IST INFO [SSH2Service.java:271] - job-1f911fa1-2966-4c65-a099-c49f28ed3092: Executing command using channel type exec
03-03-2017 16:01:57 IST ERROR [SSH2Helper.java:82] - job-1f911fa1-2966-4c65-a099-c49f28ed3092: SSHException occured while executing command : EOF received from remote side [Unknown cause]
com.sshtools.ssh.SshException: EOF received from remote side [Unknown cause]
at com.sshtools.ssh2.TransportProtocol.readWithTimeout(TransportProtocol.java:597) ~
at com.sshtools.ssh2.TransportProtocol.readMessage(TransportProtocol.java:747) ~
at com.sshtools.ssh2.TransportProtocol.nextMessage(TransportProtocol.java:571) ~
at com.sshtools.ssh.message.SshMessageRouter.blockForMessage(SshMessageRouter.java:297) ~
at com.sshtools.ssh.message.SshMessageRouter.access$000(SshMessageRouter.java:44) ~
at com.sshtools.ssh.message.SshMessageRouter$MessagePump.run(SshMessageRouter.java:370) 

```

**Comment by theGidy** [comment]
I recive this error at some point in my program. It fails while performing a change directory operation. I tought it's a timeout problem but after disabeling or setting to a high value nothing changed at all. I tried to debug it, but the error is not determinist.

**OS**: SLES 12 SP 2
**Java**: 1.6
```
 com.sshtools.ssh.SshException: EOF received from remote side [Unknown cause]
        com.sshtools.ssh2.TransportProtocol.readWithTimeout(TransportProtocol.java:597)
        com.sshtools.ssh2.TransportProtocol.readMessage(TransportProtocol.java:747)
        com.sshtools.ssh2.TransportProtocol.nextMessage(TransportProtocol.java:571)
        com.sshtools.ssh.message.SshMessageRouter.blockForMessage(SshMessageRouter.java:297)
        com.sshtools.ssh.message.SshMessageRouter.nextMessage(SshMessageRouter.java:266)
        com.sshtools.ssh.message.SshMessageStore.nextMessage(SshMessageStore.java:71)
        com.sshtools.ssh2.Ssh2Channel.processMessages(Ssh2Channel.java:507)
        com.sshtools.ssh2.Ssh2Channel$ChannelInputStream.read(Ssh2Channel.java:1132)
        com.sshtools.ssh2.Ssh2Channel$ChannelInputStream.read(Ssh2Channel.java:1097)
        java.io.DataInputStream.readInt(DataInputStream.java:370)
        com.sshtools.ssh.SubsystemChannel$Reader.readMessage(SubsystemChannel.java:212)
        com.sshtools.ssh.SubsystemChannel.nextMessage(SubsystemChannel.java:117)
        com.sshtools.sftp.SftpSubsystemChannel.getResponse(SftpSubsystemChannel.java:2025)
        com.sshtools.sftp.SftpSubsystemChannel.getAbsolutePath(SftpSubsystemChannel.java:1302)
        com.sshtools.sftp.SftpClient.cd(SftpClient.java:417)
        de.dlr.op.hf.ltdb.ingest.FileTransporterSftp.remove(FileTransporterSftp.java:642)
        ...
```

**Comment by ludup** [comment]
Can you tell me more about the server? Is it standard OpenSSH or another type of server.. do you have the servers version number?

**Comment by theGidy** [comment]
**Version of Destination Server:** 
OpenSSH_7.2p2, OpenSSL 1.0.2j-fips  26 Sep 2016

Maybe you have a good suggestion for this kind of problem.  

To reduce the impact of the destination server we will now switch to a local sftp test enviorment and try to reproduce this error in a determenistic way.

**Comment by ludup** [comment]
The ultimate cause of this is likely to be a crash on the server causing the remote process to terminate. There are not many other reasons.

When you change directory the path is validated using the SSH_FXP_REAL_PATH message (calling getAbsolutePath in the API). The server doesn't seem to be able to handle the path that is input.

**Comment by extremecode** [comment]
Hi @ludup any update on this i am also facing the same issue

**Comment by marshmello275** [comment]
Hi @ludup 
we are also facing this issue. Any workaround to solve this?

**Comment by ludup** [comment]
This version is now out of date, I do not support or maintain it anymore. I would recommend moving to the Maverick Synergy API which supersedes this. You can find it at https://github.com/sshtools/maverick-synergy.
